version: '3.8'

services:
  backend:
    build:
      context: .
      network: host
    container_name: backend
    network_mode: host
    ports:
      - "8080:8080"
    volumes:
      - ./assets:/app/image
    restart: unless-stopped
