.PHONY: run help

help:
	@echo "Available commands:"
	@echo "  make run    - Run the application (go run ../core/main.go)"
	@echo "  make help   - Show this help message"
	@echo "  make all    - Run the application (same as make run)"

run:
	go run ../core/main.go

all: run
